### ISSUE TITLE
Issue-refactor project

### ISSUE THREAD

**Issue by uneoka0114** [Johnhvy/pinghub-explorer#12]
Automated Review Comments
Issues in packages/dashboard/src/layouts/blank.vue:
  - (2, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/DefaultLayoutWithHorizontalNav.vue:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/DefaultLayoutWithVerticalNav.vue:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/Footer.vue:
  - (11, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/NavBarI18n.vue:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/NavBarNotifications.vue:
  - (2, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/NavSearchBar.vue:
  - (2, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/NavbarShortcuts.vue:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/NavbarThemeSwitcher.vue:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/UserProfile.vue:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/default.vue:
  - (2, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in packages/dashboard/src/main.ts:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in packages/dashboard/src/modules/[chain]/test.vue:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
Issues in packages/dashboard/src/pages/[...all].vue:
  - (2, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
Issues in packages/dashboard/src/pages/index.vue:
  - (11, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/router/index.ts:
  - (28, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
