### ISSUE TITLE
Issue-improve framework

### ISSUE THREAD

**Issue by uneoka0114** [Johnhvy/pinghub-explorer#14]
Automated Review Comments
Issues in packages/dashboard/package.json:
  - (6, 'Hardcoded string found')
Issues in packages/dashboard/public/logo.svg:
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (236, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/assets/logo.svg:
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/layouts/components/DefaultLayout.vue:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/Footer.vue:
  - (8, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/default.vue:
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/navigation/index.ts:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in packages/dashboard/src/libs/http.ts:
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/modules/[chain]/test.vue:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
Issues in packages/dashboard/src/pages/second-page.vue:
  - (5, 'Hardcoded string found')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/components.ts:
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/components/VerticalNav.vue:
  - (4, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/components/VerticalNavGroup.vue:
  - (2, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/components/VerticalNavLink.vue:
  - (2, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/components/VerticalNavSectionTitle.vue:
  - (2, 'Hardcoded string found')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/composable/useLayouts.ts:
  - (3, 'Hardcoded string found')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/index.ts:
  - (2, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/types.d.ts:
  - (6, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in packages/dashboard/themeConfig.ts:
  - (10, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
Issues in yarn.lock:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
