### ISSUE TITLE
Issue-finish home page

### ISSUE THREAD

**Issue by uneoka0114** [Johnhvy/pinghub-explorer#16]
Automated Review Comments
Issues in packages/dashboard/src/components/ChainSummary.vue:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/DefaultLayout.vue:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
Issues in packages/dashboard/src/main.ts:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in packages/dashboard/src/pages/index.vue:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/plugins/vuetify/@core/scss/template/_variables.scss:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/components/VerticalNav.vue:
  - (1, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/components/VerticalNavGroup.vue:
  - (1, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/utils.ts:
  - (1, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/router/index.ts:
  - (24, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/stores/useBlockchain.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in packages/dashboard/src/stores/useDashboard.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
Issues in packages/dashboard/themeConfig.ts:
  - (9, 'Line exceeds 80 characters')
Issues in yarn.lock:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')

**Comment by bairmarke75** [comment]
I got it.
