### ISSUE TITLE
Issue-add i18n

### ISSUE THREAD

**Issue by uneoka0114** [Johnhvy/pinghub-explorer#18]
Automated Review Comments
Issues in packages/dashboard/auto-imports.d.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
Issues in packages/dashboard/package.json:
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/ChainProfile.vue:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/DefaultLayout.vue:
  - (1, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/layouts/components/NavBarI18n.vue:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/NavSearchBar.vue:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in packages/dashboard/src/pages/index.vue:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in packages/dashboard/src/plugins/i18n/index.ts:
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in packages/dashboard/src/plugins/i18n/locales/cn.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in packages/dashboard/src/plugins/i18n/locales/en.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in packages/dashboard/src/plugins/vuetify/@core/components/I18n.vue:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/components/VerticalNavGroup.vue:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in packages/dashboard/src/plugins/vuetify/@layouts/components/VerticalNavLink.vue:
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in packages/dashboard/src/stores/useBlockchain.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/stores/useDashboard.ts:
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
Issues in packages/dashboard/themeConfig.ts:
  - (1, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
Issues in packages/dashboard/vite.config.ts:
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
Issues in yarn.lock:
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (119, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (124, 'Line exceeds 80 characters')
  - (125, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (161, 'Line exceeds 80 characters')
  - (162, 'Line exceeds 80 characters')
  - (168, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (180, 'Line exceeds 80 characters')
  - (181, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (192, 'Line exceeds 80 characters')
  - (197, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (206, 'Line exceeds 80 characters')
  - (207, 'Line exceeds 80 characters')
  - (209, 'Line exceeds 80 characters')
  - (210, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (216, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (221, 'Line exceeds 80 characters')
  - (231, 'Line exceeds 80 characters')
  - (233, 'Line exceeds 80 characters')
  - (234, 'Line exceeds 80 characters')
  - (239, 'Line exceeds 80 characters')
  - (240, 'Line exceeds 80 characters')
  - (242, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (248, 'Line exceeds 80 characters')
  - (249, 'Line exceeds 80 characters')
  - (251, 'Line exceeds 80 characters')
  - (252, 'Line exceeds 80 characters')
  - (257, 'Line exceeds 80 characters')
  - (258, 'Line exceeds 80 characters')
  - (265, 'Line exceeds 80 characters')
  - (266, 'Line exceeds 80 characters')
  - (268, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (275, 'Line exceeds 80 characters')
  - (277, 'Line exceeds 80 characters')
  - (278, 'Line exceeds 80 characters')
  - (282, 'Line exceeds 80 characters')
  - (283, 'Line exceeds 80 characters')
  - (291, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
