### ISSUE TITLE
Issue-initial project

### ISSUE THREAD

**Issue by uneoka0114** [Johnhvy/pinghub-explorer#2]
Automated Review Comments
Issues in lerna.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in packages/dashboard/.eslintrc.cjs:
  - (2, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in packages/dashboard/README.md:
  - (8, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
Issues in packages/dashboard/index.html:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
Issues in packages/dashboard/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in packages/dashboard/public/logo.svg:
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/App.vue:
  - (2, 'Hardcoded string found')
Issues in packages/dashboard/src/assets/base.css:
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
Issues in packages/dashboard/src/components/HelloWorld.vue:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
Issues in packages/dashboard/src/components/TheWelcome.vue:
  - (2, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
Issues in packages/dashboard/src/components/WelcomeItem.vue:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
Issues in packages/dashboard/src/components/icons/IconCommunity.vue:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/components/icons/IconDocumentation.vue:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/components/icons/IconEcosystem.vue:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/components/icons/IconSupport.vue:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/components/icons/IconTooling.vue:
  - (2, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
Issues in packages/dashboard/src/main.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in packages/dashboard/src/modules/dashboard/router.ts:
  - (7, 'Hardcoded string found')
Issues in packages/dashboard/src/router/index.ts:
  - (2, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')

**Comment by williamddobson3** [comment]
I got it.
