### ISSUE TITLE
Issue-add a sample of bank.

### ISSUE THREAD

**Issue by uneoka0114** [Johnhvy/pinghub-explorer#24]
Automated Review Comments
Issues in packages/dashboard/package.json:
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in packages/dashboard/src/modules/[chain]/index.vue:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
Issues in packages/dashboard/src/stores/useBank.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/stores/useBankStore.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/stores/useBlockchain.ts:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in yarn.lock:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (158, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (163, 'Line exceeds 80 characters')
  - (170, 'Line exceeds 80 characters')
  - (171, 'Line exceeds 80 characters')
  - (175, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (182, 'Line exceeds 80 characters')
  - (183, 'Line exceeds 80 characters')
  - (185, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (193, 'Hardcoded string found')
  - (198, 'Line exceeds 80 characters')
  - (200, 'Hardcoded string found')
  - (205, 'Line exceeds 80 characters')
  - (206, 'Line exceeds 80 characters')
  - (210, 'Line exceeds 80 characters')
  - (211, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (216, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (221, 'Line exceeds 80 characters')
  - (225, 'Line exceeds 80 characters')
  - (226, 'Line exceeds 80 characters')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (233, 'Line exceeds 80 characters')
  - (234, 'Line exceeds 80 characters')
  - (238, 'Line exceeds 80 characters')
  - (239, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (244, 'Line exceeds 80 characters')
  - (248, 'Line exceeds 80 characters')
  - (249, 'Line exceeds 80 characters')
  - (253, 'Line exceeds 80 characters')
  - (254, 'Line exceeds 80 characters')
  - (258, 'Line exceeds 80 characters')
  - (260, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
  - (265, 'Line exceeds 80 characters')
  - (266, 'Line exceeds 80 characters')
  - (270, 'Line exceeds 80 characters')
  - (272, 'Line exceeds 80 characters')
  - (273, 'Line exceeds 80 characters')
  - (277, 'Line exceeds 80 characters')
  - (278, 'Line exceeds 80 characters')
  - (282, 'Line exceeds 80 characters')
  - (284, 'Line exceeds 80 characters')
  - (285, 'Line exceeds 80 characters')
  - (289, 'Line exceeds 80 characters')
  - (290, 'Line exceeds 80 characters')
  - (297, 'Line exceeds 80 characters')
  - (298, 'Line exceeds 80 characters')
  - (304, 'Line exceeds 80 characters')
  - (306, 'Line exceeds 80 characters')
  - (307, 'Line exceeds 80 characters')
  - (312, 'Line exceeds 80 characters')
  - (313, 'Line exceeds 80 characters')
  - (317, 'Line exceeds 80 characters')
  - (318, 'Line exceeds 80 characters')
  - (322, 'Line exceeds 80 characters')
  - (329, 'Line exceeds 80 characters')
  - (330, 'Line exceeds 80 characters')
  - (334, 'Line exceeds 80 characters')
  - (335, 'Line exceeds 80 characters')
  - (339, 'Line exceeds 80 characters')
  - (346, 'Line exceeds 80 characters')
  - (347, 'Line exceeds 80 characters')
  - (349, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (358, 'Line exceeds 80 characters')
  - (359, 'Line exceeds 80 characters')
  - (366, 'Line exceeds 80 characters')
  - (368, 'Line exceeds 80 characters')
  - (369, 'Line exceeds 80 characters')
  - (373, 'Line exceeds 80 characters')
  - (374, 'Line exceeds 80 characters')
  - (386, 'Line exceeds 80 characters')
  - (388, 'Line exceeds 80 characters')
  - (389, 'Line exceeds 80 characters')
  - (394, 'Line exceeds 80 characters')
  - (395, 'Line exceeds 80 characters')
  - (403, 'Line exceeds 80 characters')
  - (404, 'Line exceeds 80 characters')
  - (406, 'Line exceeds 80 characters')
  - (407, 'Line exceeds 80 characters')
  - (411, 'Line exceeds 80 characters')
  - (412, 'Line exceeds 80 characters')
  - (419, 'Line exceeds 80 characters')
  - (420, 'Line exceeds 80 characters')
  - (424, 'Line exceeds 80 characters')
  - (425, 'Line exceeds 80 characters')
  - (433, 'Line exceeds 80 characters')
  - (435, 'Line exceeds 80 characters')
  - (436, 'Line exceeds 80 characters')
  - (440, 'Line exceeds 80 characters')
  - (441, 'Line exceeds 80 characters')
  - (445, 'Line exceeds 80 characters')
  - (452, 'Line exceeds 80 characters')
  - (453, 'Line exceeds 80 characters')
  - (459, 'Line exceeds 80 characters')
  - (460, 'Line exceeds 80 characters')
  - (464, 'Line exceeds 80 characters')
  - (471, 'Line exceeds 80 characters')
  - (472, 'Line exceeds 80 characters')
  - (476, 'Line exceeds 80 characters')
  - (477, 'Line exceeds 80 characters')
  - (481, 'Line exceeds 80 characters')
  - (483, 'Line exceeds 80 characters')
  - (484, 'Line exceeds 80 characters')
  - (488, 'Line exceeds 80 characters')
  - (489, 'Line exceeds 80 characters')
  - (493, 'Line exceeds 80 characters')
  - (494, 'Line exceeds 80 characters')
  - (498, 'Line exceeds 80 characters')
  - (500, 'Line exceeds 80 characters')
  - (501, 'Line exceeds 80 characters')
  - (505, 'Line exceeds 80 characters')
  - (506, 'Line exceeds 80 characters')
  - (508, 'Hardcoded string found')
  - (509, 'Hardcoded string found')
  - (510, 'Hardcoded string found')
  - (511, 'Hardcoded string found')
  - (512, 'Hardcoded string found')
  - (513, 'Hardcoded string found')
  - (519, 'Line exceeds 80 characters')
  - (521, 'Line exceeds 80 characters')
  - (522, 'Line exceeds 80 characters')
  - (526, 'Line exceeds 80 characters')
  - (527, 'Line exceeds 80 characters')
  - (529, 'Hardcoded string found')
  - (530, 'Hardcoded string found')
  - (531, 'Hardcoded string found')
  - (532, 'Hardcoded string found')
  - (533, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (535, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (537, 'Hardcoded string found')
  - (538, 'Hardcoded string found')
  - (539, 'Hardcoded string found')
  - (540, 'Hardcoded string found')
  - (545, 'Line exceeds 80 characters')
  - (552, 'Line exceeds 80 characters')
  - (553, 'Line exceeds 80 characters')
  - (557, 'Line exceeds 80 characters')
  - (564, 'Line exceeds 80 characters')
  - (565, 'Line exceeds 80 characters')
  - (569, 'Line exceeds 80 characters')
  - (576, 'Line exceeds 80 characters')
  - (577, 'Line exceeds 80 characters')
  - (581, 'Line exceeds 80 characters')
  - (582, 'Line exceeds 80 characters')
  - (586, 'Line exceeds 80 characters')
  - (587, 'Line exceeds 80 characters')
  - (594, 'Line exceeds 80 characters')

**Comment by stevesjones813** [comment]
I got it.
