### ISSUE TITLE
Issue-add balance cache

### ISSUE THREAD

**Issue by uneoka0114** [Johnhvy/pinghub-explorer#26]
Automated Review Comments
Issues in packages/dashboard/src/components/ChainSummary.vue:
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in packages/dashboard/src/layouts/components/ChainProfile.vue:
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
Issues in packages/dashboard/src/pages/index.vue:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
Issues in packages/dashboard/src/stores/useBank.ts:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/stores/useBankStore.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/stores/useBlockchain.ts:
  - (1, 'Line exceeds 80 characters')
  - (1, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in packages/dashboard/src/stores/useDashboard.ts:
  - (80, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (123, 'Hardcoded string found')

**Comment by billmbowling3** [comment]
I got it.
