### ISSUE TITLE
Issue-add client extension support

### ISSUE THREAD

**Issue by uneoka0114** [Johnhvy/pinghub-explorer#28]
Automated Review Comments
Issues in packages/codegen/.telescope.json:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in packages/codegen/dist/confio/proofs.d.ts:
  - (5, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (108, 'TODO found')
  - (114, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (200, 'Line exceeds 80 characters')
  - (201, 'Line exceeds 80 characters')
  - (211, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (222, 'Line exceeds 80 characters')
  - (223, 'Line exceeds 80 characters')
  - (237, 'Line exceeds 80 characters')
  - (246, 'Line exceeds 80 characters')
  - (250, 'Line exceeds 80 characters')
  - (252, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
  - (274, 'Line exceeds 80 characters')
  - (293, 'Line exceeds 80 characters')
  - (299, 'Line exceeds 80 characters')
  - (356, 'Line exceeds 80 characters')
  - (366, 'TODO found')
  - (423, 'Line exceeds 80 characters')
  - (424, 'Line exceeds 80 characters')
  - (428, 'Line exceeds 80 characters')
  - (429, 'Line exceeds 80 characters')
  - (433, 'Line exceeds 80 characters')
  - (434, 'Line exceeds 80 characters')
  - (437, 'Line exceeds 80 characters')
  - (438, 'Line exceeds 80 characters')
  - (439, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/app/v1alpha1/config.d.ts:
  - (11, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/app/v1alpha1/module.d.ts:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/app/v1alpha1/query.d.ts:
  - (22, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/auth/v1beta1/auth.d.ts:
  - (2, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/auth/v1beta1/query.d.ts:
  - (2, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')
  - (125, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (133, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (164, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (174, 'Line exceeds 80 characters')
  - (175, 'Line exceeds 80 characters')
  - (179, 'Line exceeds 80 characters')
  - (184, 'Line exceeds 80 characters')
  - (185, 'Line exceeds 80 characters')
  - (188, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (190, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (194, 'Line exceeds 80 characters')
  - (195, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (199, 'Line exceeds 80 characters')
  - (200, 'Line exceeds 80 characters')
  - (203, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (205, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/auth/v1beta1/query.lcd.d.ts:
  - (3, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/auth/v1beta1/query.rpc.Query.d.ts:
  - (4, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/authz/v1beta1/authz.d.ts:
  - (10, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/authz/v1beta1/query.d.ts:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/authz/v1beta1/query.lcd.d.ts:
  - (3, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/authz/v1beta1/query.rpc.Query.d.ts:
  - (4, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/authz/v1beta1/tx.d.ts:
  - (7, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/authz/v1beta1/tx.rpc.msg.d.ts:
  - (3, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/bank/v1beta1/bank.d.ts:
  - (74, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (125, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/bank/v1beta1/genesis.d.ts:
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/bank/v1beta1/query.d.ts:
  - (2, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (163, 'Line exceeds 80 characters')
  - (167, 'Line exceeds 80 characters')
  - (172, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (181, 'Line exceeds 80 characters')
  - (187, 'Line exceeds 80 characters')
  - (194, 'Line exceeds 80 characters')
  - (199, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (212, 'Line exceeds 80 characters')
  - (219, 'Line exceeds 80 characters')
  - (224, 'Line exceeds 80 characters')
  - (230, 'Line exceeds 80 characters')
  - (258, 'Line exceeds 80 characters')
  - (264, 'Line exceeds 80 characters')
  - (271, 'Line exceeds 80 characters')
  - (276, 'Line exceeds 80 characters')
  - (277, 'Line exceeds 80 characters')
  - (281, 'Line exceeds 80 characters')
  - (282, 'Line exceeds 80 characters')
  - (286, 'Line exceeds 80 characters')
  - (287, 'Line exceeds 80 characters')
  - (290, 'Line exceeds 80 characters')
  - (291, 'Line exceeds 80 characters')
  - (292, 'Line exceeds 80 characters')
  - (295, 'Line exceeds 80 characters')
  - (296, 'Line exceeds 80 characters')
  - (297, 'Line exceeds 80 characters')
  - (301, 'Line exceeds 80 characters')
  - (302, 'Line exceeds 80 characters')
  - (306, 'Line exceeds 80 characters')
  - (307, 'Line exceeds 80 characters')
  - (311, 'Line exceeds 80 characters')
  - (312, 'Line exceeds 80 characters')
  - (316, 'Line exceeds 80 characters')
  - (317, 'Line exceeds 80 characters')
  - (321, 'Line exceeds 80 characters')
  - (326, 'Line exceeds 80 characters')
  - (330, 'Line exceeds 80 characters')
  - (331, 'Line exceeds 80 characters')
  - (332, 'Line exceeds 80 characters')
  - (335, 'Line exceeds 80 characters')
  - (336, 'Line exceeds 80 characters')
  - (337, 'Line exceeds 80 characters')
  - (340, 'Line exceeds 80 characters')
  - (341, 'Line exceeds 80 characters')
  - (342, 'Line exceeds 80 characters')
  - (345, 'Line exceeds 80 characters')
  - (346, 'Line exceeds 80 characters')
  - (347, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (352, 'Line exceeds 80 characters')
  - (361, 'Line exceeds 80 characters')
  - (362, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/bank/v1beta1/query.lcd.d.ts:
  - (3, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/bank/v1beta1/query.rpc.Query.d.ts:
  - (4, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/bank/v1beta1/tx.d.ts:
  - (57, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/bank/v1beta1/tx.rpc.msg.d.ts:
  - (3, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
Issues in packages/codegen/dist/cosmos/base/abci/v1beta1/abci.d.ts:
  - (2, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (199, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (278, 'Line exceeds 80 characters')

**Comment by brandonabeal110** [comment]
I got it.
