### ISSUE TITLE
Issue-rpc endpoint version

### ISSUE THREAD

**Issue by uneoka0114** [Johnhvy/pinghub-explorer#37]
Automated Review Comments
Issues in packages/dashboard/chains/mainnet/cosmos.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
Issues in packages/dashboard/src/components/ProposalProcess.vue:
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
Issues in packages/dashboard/src/components/ValidatorCommissionRate.vue:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
Issues in packages/dashboard/src/components/dynamic/ArrayBytesElement.vue:
  - (2, 'Hardcoded string found')
Issues in packages/dashboard/src/components/dynamic/ArrayElement.vue:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in packages/dashboard/src/components/dynamic/ArrayObjectElement.vue:
  - (2, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in packages/dashboard/src/components/dynamic/DynamicComponent.vue:
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in packages/dashboard/src/components/dynamic/NumberElement.vue:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in packages/dashboard/src/components/dynamic/ObjectElement.vue:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
Issues in packages/dashboard/src/components/dynamic/TextElement.vue:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in packages/dashboard/src/components/dynamic/TxsElement.vue:
  - (2, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/components/dynamic/UInt8Array.vue:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/components/dynamic/index.ts:
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in packages/dashboard/src/libs/address.ts:
  - (4, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/libs/client.rpc.ts:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/libs/misc.ts:
  - (4, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/modules/[chain]/block/[height].vue:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
Issues in packages/dashboard/src/modules/[chain]/block/block.ts:
  - (2, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/modules/[chain]/block/index.vue:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
Issues in packages/dashboard/src/modules/[chain]/index.vue:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/modules/[chain]/indexStore.ts:
  - (1, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/modules/[chain]/staking/[validator].vue:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (102, 'Hardcoded string found')
  - (105, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (119, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (140, 'Hardcoded string found')
  - (141, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (156, 'Line exceeds 80 characters')
  - (157, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (162, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (163, 'Line exceeds 80 characters')
  - (170, 'Line exceeds 80 characters')
  - (170, 'Hardcoded string found')
  - (171, 'Line exceeds 80 characters')
  - (178, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (179, 'Line exceeds 80 characters')
  - (180, 'Line exceeds 80 characters')
  - (180, 'Hardcoded string found')
  - (195, 'Line exceeds 80 characters')
  - (198, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (211, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (219, 'Line exceeds 80 characters')
  - (223, 'Line exceeds 80 characters')
  - (229, 'Hardcoded string found')
  - (241, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (243, 'Hardcoded string found')
Issues in packages/dashboard/src/modules/[chain]/staking/index.vue:
  - (6, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (119, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (139, 'Hardcoded string found')
  - (144, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/modules/[chain]/tx/[hash].vue:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
Issues in packages/dashboard/src/stores/useBaseStore.ts:
  - (1, 'Hardcoded string found')
Issues in packages/dashboard/src/stores/useBlockchain.ts:
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in packages/dashboard/src/stores/useFormatter.ts:
  - (4, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
Issues in packages/dashboard/src/stores/useGovStore.ts:
  - (1, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
Issues in packages/dashboard/src/stores/useMintStore.ts:
  - (2, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in packages/dashboard/src/stores/useStakingStore.ts:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')

**Comment by billmbowling3** [comment]
I got it.
